### ISSUE TITLE
I just don't know why ?

### ISSUE THREAD

**Issue by KlausStortebeker** [ionghitun/laravel-lumen-mysql-encryption#3]
Why you will encrypt the database if you give the key to decrypt it in plain text ?

**Comment by ionghitun** [comment]
The key theoretically it's on another server, not where you store the database, this is an extra layer of protection for sensitive data in case someone breaks your database.

**Comment by KlausStortebeker** [comment]
Yeah but that is a problem that theoretically can't exist , how can be the database server accessed by some random people when you can block it by firewall to the app server only access , so the random people need to have access to the app server in the first place so now he had access to the key and all the data .
