### ISSUE TITLE
Scopes support with Query Builder ?

### ISSUE THREAD

**Issue by UsamaKhan-hub** [ionghitun/laravel-lumen-mysql-encryption#4]
Hello, first of all thanks for this wonderful package. just stuck at a point, is there any way we could use these predefined scopes with query  builder ? its working with ORM but not with query builder . Thanks.

**Comment by ionghitun** [comment]
Thank you, I will look into this.

**Comment by ionghitun** [comment]
@UsamaKhan-hub there are this predefined scopes within project

```
    whereEncrypted
    whereNotEncrypted
    orWhereEncrypted
    orWhereNotEncrypted
    orderByEncrypted
```

You can use them as any other custom scopes, ex: `$model->whereEncrypted('test');`

Are those enough or what exactly do you meant by this issue?

**Comment by UsamaKhan-hub** [comment]
@ionghitun  Sir these predefined scopes works well with ORM but my point is, with query builder it doesn't work. 
E.g. DB::table('xyz')->whereEncrypted('email', $input->email) 
Here Query Builder fails when i use any of these predefined scopes. 
 **Second query :**
If we simply get users from a model using ORM
E.g  User::all() 
This packages automatically decrypt the data for us. Which is quite good. Because we defined 'encrypted' property in the User Model. 
But again, with query Builder DB::table('users')->get(); 
It returns the encrypted data. 
So, i know we can achieve this by some custom method, 
But if you can provide support of these predefined scopes with query Builder, that would be great because there some cases where i have to manipulate data with query builder. 
I hope so, you got my point. Thank you.

**Comment by ionghitun** [comment]
@UsamaKhan-hub Sir, I understand you, after a research this is not possible to add to this package, the DB facade doesn't have any support to any custom functions, scopes or something that would help process your request, I am really sorry!
