### ISSUE TITLE
"message": "Malformed UTF-8 characters, possibly incorrectly encoded",

### ISSUE THREAD

**Issue by UsamaKhan-hub** [ionghitun/laravel-lumen-mysql-encryption#5]
Hello, im facing this issue, fetching data with laravel relationship and when returning response i got this error. Kindly guide me. 

//controller
  $group = ContactGroup::with(['contacts' => function ($query) use ($select_fields) {
            $query->select($select_fields);
        }])->findOrFail($id);

        return $this->successResponse(
            ['model' => $this->model],
            __('contacts.contact.success_fetched'),
            ["contacts_group" =>$group]
        );
    }
    
    "response consist : data->contact_group->contacts "
   Contacts is relation. 
   Thanks.

**Comment by ionghitun** [comment]
Hi @UsamaKhan-hub can you show me what's in encrypted attribute for ContactGroup and Contact model?

**Comment by UsamaKhan-hub** [comment]
> Hi @UsamaKhan-hub can you show me what's in encrypted attribute for ContactGroup and Contact model?

**ContactGroup model just have foreign keys so i didnt use encryptable array, and in contact model i have placed many attributes in encryptable array**
When fetching only contacts data like : Contact::latest()->first() and then return response i didnt find any difficulty to return data but using relation , i am facing malformed utf8 issue. 

**You can see the below relation response on contacts data**
 #relations: array:1 [
    "contacts" => Illuminate\Database\Eloquent\Collection {#1839
      #items: array:2 [
        0 => App\Models\Tenants\Contacts\Contact {#1860
          #connection: "tenant"
          #table: "contacts"
          #primaryKey: "id"
          #keyType: "int"
          +incrementing: true
          #with: []
          #withCount: []
          +preventsLazyLoading: false
          #perPage: 15
          +exists: true
          +wasRecentlyCreated: false
          #escapeWhenCastingToString: false
          #attributes: array:23 [
            "id" => 1
            "contact_board_id" => 1
            "contact_group_id" => 1
            "title" => b"±$á{+\x1DºûE]½š%F\x06Å"
            "first_name" => b"@▄èÕ▓xM³└\x0Eha)┼ìı\e,\fWÏÇ\x11\x15\x05*K~aÇòz"
            "surname" => b"!õ‡±q9\x08z\x1A%fyPl\x19¦"
            "email" => b"\x16j▒òÃ┬┌ý×\x05zÉv┤Õ¸\x12_%┘Ë\x1FG´¤×╠R-÷ÚZ"
            "address_1" => b"aÉUÉÀ¬║IÔ\x03Ó?¹äÓ"®■7╔\x04RÞ╠±\x14\x19¶├¬ï┼d/é■\x04è¿─DÓ½æ¿i╚\x06n│▓ëS¼HGı£§T└*ÿ\v"
            "address_2" => b"r\x14é½—ÈHdBNU³Ñ\x03“ªÃlKlß}Ef*N½‹Ô]Ÿ\x1F[kZpiÎVî3ZÉ‡&8M0\x02èo;ËÙÎ¾ò»LÊÓ™ÞH"
            "postcode" => b"VYªól;\x13\x19Ñ¶&\x13çm\2"
            "town_city" => b"fºû+£v\x13ÐHühR'Y\x1DÅ"
            "state" => b"œkoäÉë“\x1AäuÛE¡¢[¸"

**Comment by ionghitun** [comment]
Ok, thanks, will look into that asap!

**Comment by UsamaKhan-hub** [comment]
> Ok, thanks, will look into that asap!

Sure, thanks for responding.

**Comment by ionghitun** [comment]
Tried to test is this way:
```
$parent = Parent::with(['child' =>function($query) {
	$query->select(['id','parentid', 'encrypted_field']);
} ])->find(1);

dd($parent->toJson());
dd($parent->toArray());
```
And it worked perfect for me, can you try grabbing only one, maybe check your data, you can use a query like this directly in db:
`SELECT AES_DECRYPT(encrypted_column, 'ENCRYPTION_KEY') FROM table WHERE ...`

**Comment by UsamaKhan-hub** [comment]
> Tried to test is this way:
> 
> ```
> $parent = Parent::with(['child' =>function($query) {
> 	$query->select(['id','parentid', 'encrypted_field']);
> } ])->find(1);
> 
> dd($parent->toJson());
> dd($parent->toArray());
> ```
> 
> And it worked perfect for me, can you try grabbing only one, maybe check your data, you can use a query like this directly in db: `SELECT AES_DECRYPT(encrypted_column, 'ENCRYPTION_KEY') FROM table WHERE ...`

Ughh perfect, i wasnt looking with that aspect, actually i was calling  function which was returing data **withprefix** , **withoutprefix** and **alias** like if there's **vn_title**, so in $select_filed['alias'] it was returning **contacts.vn_title** , i passed array without prefix , it working smoothly now.  Thanks again.
