### ISSUE TITLE
How to decrypt data from sql query ? is there any  way of doing it ? 

### ISSUE THREAD

**Issue by muhammad-salman-khalid** [ionghitun/laravel-lumen-mysql-encryption#6]
I am writing raw sql query and fetching results .I know on query builder there is no such thing but what I want is that after getting data in php variable how can I decrypt it using your package .?

I am getting this 
![image](https://user-images.githubusercontent.com/44359501/192773530-5589841c-82c8-4f39-a244-9b33ee1ee08f.png)

**Comment by ionghitun** [comment]
Hi, if you are using a Model that extends my BaseModel, you can use $this->aesDecrypt($value), you should keep in mind if the data wasn't encrypted with my package or not using the same ENCRYPTION_KEY or CYPHER you might not have the wanted result.
